version: '3.7'

services:
  mongo:
    image: mongo
    container_name: mongo_trends
    restart: always
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: trends

volumes:
  mongo: