version: '3.7'

services:
  mongo:
    image: mongo:4.2
    container_name: trends_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    env_file:
      - .env

volumes:
  mongo:
